name: SSH Actions

on:
  workflow_dispatch:

jobs:
  ssh-session:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Start Session
        run: |
          sudo apt update
          sudo apt install -y tmate python3
          tmate
